version: '3.8'

services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - backend
      - db
    networks:
      - network

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../../backend:/var/www
    working_dir: /var/www
    container_name: backend
    networks:
      - network

  backend-proxy:
    build:
      context: ../../
      dockerfile: ./deploy/dev/backend-proxy/Dockerfile
    container_name: backend-proxy
    hostname: backend-proxy
    volumes:
      - ./../../backend/storage/app/public/:/var/www/public/storage/app/public
    networks:
      - network

  adminer:
    image: adminer:latest
    ports:
      - '${ADMINER_PORT:-8081}:8081'
    networks:
      - network

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../deploy/dev/node/Dockerfile
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

networks:
  network:

volumes:
  db_data: